#!/bin/bash

docker build --tag emso "$(dirname ${BASH_SOURCE[0]})"
docker run \
    --env "UID=$UID" \
    --env "DISPLAY=$DISPLAY" \
    --volume "/tmp/.X11-unix:/tmp/.X11-unix" \
    --volume "$HOME:/home/developer" \
    emso
