#!/bin/bash

DOCKER_IMAGE_TAG=tassoevan/emso:$(git rev-parse HEAD)

docker build --tag "$DOCKER_IMAGE_TAG" "$(dirname ${BASH_SOURCE[0]})"
docker run \
    --env "UID=$UID" \
    --env "DISPLAY=$DISPLAY" \
    --volume "/tmp/.X11-unix:/tmp/.X11-unix" \
    --volume "$HOME:/home/developer" \
    "$DOCKER_IMAGE_TAG"
